### ISSUE TITLE
Benefit from static analysis

### ISSUE THREAD

**Issue by szepeviktor** [webimpress/coding-standard#52]
Hello!
You may reach very robust code by using @phpstan

`phpstan.neon.dist`

```yaml
#$ composer require --dev phpstan/phpstan-shim
#$ phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
parameters:
    level: 2
#    level: 4
#    level: max
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
#        - %currentWorkingDirectory%/test/
    ignoreErrors:
        #
        # These are way too easy to fix!
        - '#^Variable \$\S+ might not be defined\.$#'
        - '#^Access to an undefined property WebimpressCodingStandard\\\S+\.$#'
```
